apiVersion: v1/v1beta1
kink: Deployment
metadata: 
  name: hello-nginx
spec: 
  template: #configurações do pod
    metadata:
        labels: 
          app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80