apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: hello-nginx
spec: 
  replicas: 2 #Define a quantidade de pods que será criado
  template: #configurações do pod
    metadata:
        labels: 
          app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80

        volumeMounts: #Configurações de montagem do volume
        - mountPath: /etc/nginx/conf.d #Caminho onde o volume será montando no container
          name: nginx-conf #Nome do volume que será montado
          readOnly: true #Somente leitura, não pode fazer alteração nesse volume
      
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf #Nome configurado no arquivo configmap.yaml
          items:
          - key: nginx.conf #A key configurada no arquivo configmap.yaml logo abaixo da tag data
            path: nginx.conf #Nome do arquivo que será gerado no volume quando montado