apiVersion: apps/v1
kink: Deployment
metadata: 
  name: mysql-server
spec: #Especificação do deployment
  replicas: 1

  selector: #Selector utilizado para criar o service
    matchLabels:
      app: mysql-server
      tier: db

  template: #Referente ao pod
   metadata: #Metadata utilizada nos pods
    labels: 
      app: mysql-server
      tier: db
  spec: #spec do pod
    cotainers:
    - image: mysql:5.7
      name: mysql-server
      args:
        -"--ignore-db-dir=lost+found" #Comenado para ignorar o arquivo lost found
      
      env: #Variáveis de ambiente
      - name: MYSQL_ROOT_PASSWORD
        valueFrom: # Para usar a senha do mysql como secret, é necessário rodar o comando (kubectl create secret generic mysql-pass --from-literal=password='valor da senha')
          secretKeyRef:
            name: mysql-pass #Nome do secret
            key: password #Valor do secret
      
      ports: #Porta do container
      - containerPort: 3306
      
      volumeMounts: #Monta o volume
      - name: mysql-persistent-storage
      mounthPath: /var/lib/mysql
    

    volumes: #definição do volume
    - name: mysql-persistent-storage
      persistentVolumeCalim:
        claimName: mysql-pdv-claim