apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
spec: #Especificação do deployment
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

#Comando para criar senha do mysql e armazenar no config.map
#kubectl create secret generic mysql-pass --from-literal=password='a1s2d3f4'