apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec: #Especificação do service
  ports:
    - port: 3306
  selector: #Selector utilizado para criar o service
    app: mysql-server
    tier: db
  clusterIP: None #Não deixa que seja acessado externamente